name: 'SWM GitHub Actions Basic'

on: push
env:
  WORKFLOW_LEVEL: "This value comes from the WORKFLOW_LEVEL"
  PRESET_VALUE: "This is the preset value"
jobs:
  first-job: 
    name: 'First Job'
    runs-on: ubuntu-latest

    steps:
    - name: 'Say Hello World 1'
      shell: bash
      run: |
        var_1="This is the value 1 in the step 1"

        echo "STEPSET_VALUE_1=$var_1" >> $GITHUB_ENV

    - name: 'Say Hello World 2'
      shell: pwsh
      run: |
        $var_2 = "This is the value 2 in the step 2"

        echo "STEPSET_VALUE_2=$var_2" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
        
    - name: Check environment variables
      shell: bash
      run: |
        echo "preset value: ${{ env.PRESET_VALUE }}"
        echo "stepset value: ${{ env.STEPSET_VALUE_1 }}"
        echo "stepset value: ${{ env.STEPSET_VALUE_2 }}"


    