name: 'SWM GitHub Actions Basic'

on: 
  push:
    branches:
      - master
      - main
      - 'feature/*'
      - 'release/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  

jobs:
  first-job: 
    name: 'First Job'
    if: github.event_name == 'push'

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        message: [ 'HELLO WORLD', 'LOREM IPSUM']

    runs-on: ${{ matrix.os }}

    steps:
    - name: 'Set output value'
      id: first
      shell: bash
      run: |
        var_1="This is the value: ${{ matrix.message }}"

        echo "::add-mask::$var_1"
        echo "::set-output name=first_value::$var_1"

    - name: 'Check output value on ${{ matrix.os }}'
      if: matrix.os == 'ubuntu-latest'
      shell: pwsh
      run: |
        echo "${{ steps.first.outputs.first_value }}"


    