name: 'SWM GitHub Actions Basic'

on: 
  push:
    branches:
      - master
  

jobs:
  first-job: 
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: "Send message to webex Space"
      shell: bash
      uses: ./
      with:
        webexToken: ${{ secrets.WEBEX_TOKEN }}
        webexRoomId: ${{ secrets.WEBEX_ROOM_ID }}
        bodyText: "Message sent by GitHub Actions from ${{ github.repository }}"
        bodyMarkdown: "Message sent by **GitHub Actions** from ${{ github.repository }}"
        
      # run: |
      #   curl --location --request POST 'https://webexapis.com/v1/messages' \
      #   --header 'Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}' \
      #   --header 'Content-Type: application/json' \
      #   --data-raw '{
      #     "roomId": "${{ secrets.WEBEX_ROOM_ID }}",
      #     "text": "Message sent by GitHub Actions from ${{ github.repository }}"
      #   }'