name: 'SWM GitHub Actions Basic'

on: push
env:
  WORKFLOW_LEVEL: "This value comes from the WORKFLOW_LEVEL"

jobs:
  first-job: 
    name: 'First Job'
    runs-on: ubuntu-latest

    steps:
    - name: 'Say Hello World 1'
      shell: bash
      env:
        STEP_LEVEL_11: "This value comes from the STEP level 11"
      run: |
        echo "WORKFLOW: $WORKFLOW_LEVEL"
        echo "JOB 1: $env:JOB_LEVEL_1"
        echo "JOB 2: $JOB_LEVEL_2"
        echo "STEP 11: ${{ env.STEP_LEVEL_11 }}"
        echo "STEP 12: $STEP_LEVEL_12"
        echo "STEP 21: $STEP_LEVEL_21"
        echo "STEP 22: $STEP_LEVEL_22"

    - name: 'Say Hello World 2'
      shell: pwsh
      env:
        STEP_LEVEL_12: "This value comes from the STEP level 12"
      run: |
        echo "Hello World from step 2"
        echo "JOB 1: $env:JOB_LEVEL_1"
        echo "JOB 2: $JOB_LEVEL_2"
        echo "STEP 11: $STEP_LEVEL_11"
        echo "STEP 12: $STEP_LEVEL_12"
        echo "STEP 21: $STEP_LEVEL_21"
        echo "STEP 22: $STEP_LEVEL_22"

  second-job: 
    name: 'Second Job'
    runs-on: ubuntu-latest

    steps:
    - name: 'Say Hello World 2'
      shell: bash
      env:
        STEP_LEVEL_21: "This value comes from the STEP level 11"
      run: |
        echo "WORKFLOW: $WORKFLOW_LEVEL"
        echo "JOB 1: $JOB_LEOVE_1"
        echo "JOB 2: $JOB_LEOVE_2"
        echo "STEP 11: $STEP_LEVEL_11"
        echo "STEP 12: $STEP_LEVEL_12"
        echo "STEP 21: $STEP_LEVEL_21"
        echo "STEP 22: $STEP_LEVEL_22"

    - name: 'Say Hello World 2'
      shell: pwsh
      env:
        STEP_LEVEL_22: "This value comes from the STEP level 12"
      run: |
        echo "Hello World from step 2"
        echo "WORKFLOW: $WORKFLOW_LEVEL"
        echo "JOB 1: $JOB_LEOVE_1"
        echo "JOB 2: $JOB_LEOVE_2"
        echo "STEP 11: $STEP_LEVEL_11"
        echo "STEP 12: $STEP_LEVEL_12"
        echo "STEP 21: $STEP_LEVEL_21"
        echo "STEP 22: $STEP_LEVEL_22"
    